/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

/**
 *
 * @author shree
 */
public class FunctionPointsPanel extends javax.swing.JPanel {

    /**
     * Creates new form FunctionPointsPanel
     */
    private String currentLanguage = null;
    
    private int[] vafValues = new int[14];
    private int vafSum = 0;

    private void refreshVafUI() {
        jTextField14.setText(String.valueOf(vafSum)); // using your jTextField14 for VAF sum
    }

    private void refreshCurrentLanguageUI() {
        String shown = (currentLanguage == null || currentLanguage.isBlank()) ? "None" : currentLanguage;
        jTextField12.setText(shown);
        refreshVafUI();
    }
    
    public void setCurrentLanguage(String lang) {
    currentLanguage = (lang == null || lang.isBlank()) ? "None" : lang;
    refreshCurrentLanguageUI();
    }

    public String getCurrentLanguage() {
        return currentLanguage;
    }

    public FunctionPointsPanel() {
        initComponents();
        refreshCurrentLanguageUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private int locPerFp(String lang) {
        if (lang == null) return -1;
        return switch (lang) {
            case "Assembler" -> 320;
            case "Ada 95" -> 70;
            case "C" -> 128;
            case "C++" -> 64;
            case "C#" -> 58;
            case "COBOL" -> 80;
            case "FORTRAN" -> 105;
            case "HTML" -> 15;
            case "Java" -> 53;
            case "JavaScript" -> 47;
            case "VBScript" -> 38;
            case "Visual Basic" -> 50;
            default -> -1;
        };
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jTextField6 = new javax.swing.JTextField();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jTextField7 = new javax.swing.JTextField();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jTextField8 = new javax.swing.JTextField();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jTextField9 = new javax.swing.JTextField();
        jRadioButton13 = new javax.swing.JRadioButton();
        jRadioButton14 = new javax.swing.JRadioButton();
        jRadioButton15 = new javax.swing.JRadioButton();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(900, 600));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Weighting Factors");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel2.setText("Simple");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel3.setText("Average");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel4.setText("Complex");

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel5.setText("External Inputs");

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel6.setText("External Outputs");

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel7.setText("External Inquiries");

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel8.setText("Internal Logical Files");

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel9.setText("External Interface Files");

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel10.setText("Total Count");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("3");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("4");

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("6");

        jTextField6.setEditable(false);
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButton4);
        jRadioButton4.setText("4");

        buttonGroup2.add(jRadioButton5);
        jRadioButton5.setText("5");

        buttonGroup2.add(jRadioButton6);
        jRadioButton6.setText("7");

        jTextField7.setEditable(false);

        buttonGroup4.add(jRadioButton7);
        jRadioButton7.setText("7");

        buttonGroup3.add(jRadioButton8);
        jRadioButton8.setText("4");

        buttonGroup3.add(jRadioButton9);
        jRadioButton9.setText("6");

        jTextField8.setEditable(false);

        buttonGroup5.add(jRadioButton10);
        jRadioButton10.setText("5");

        buttonGroup4.add(jRadioButton11);
        jRadioButton11.setText("10");

        buttonGroup4.add(jRadioButton12);
        jRadioButton12.setText("15");

        jTextField9.setEditable(false);

        buttonGroup3.add(jRadioButton13);
        jRadioButton13.setText("3");

        buttonGroup5.add(jRadioButton14);
        jRadioButton14.setText("7");

        buttonGroup5.add(jRadioButton15);
        jRadioButton15.setText("10");

        jTextField10.setEditable(false);

        jTextField11.setEditable(false);

        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jButton1.setText("Compute FP");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jButton2.setText("Value Adjustments");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jButton3.setText("Compute Code Size");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jButton4.setText("Change Language");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 1, 13)); // NOI18N
        jLabel11.setText("Current  Language");

        jTextField12.setEditable(false);

        jTextField13.setEditable(false);

        jTextField14.setEditable(false);

        jTextField15.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(390, 390, 390)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(360, 360, 360)
                        .addComponent(jLabel2)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel3)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel5)
                        .addGap(70, 70, 70)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103)
                        .addComponent(jRadioButton1)
                        .addGap(50, 50, 50)
                        .addComponent(jRadioButton2)
                        .addGap(62, 62, 62)
                        .addComponent(jRadioButton3)
                        .addGap(94, 94, 94)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel6)
                        .addGap(57, 57, 57)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103)
                        .addComponent(jRadioButton4)
                        .addGap(50, 50, 50)
                        .addComponent(jRadioButton5)
                        .addGap(62, 62, 62)
                        .addComponent(jRadioButton6)
                        .addGap(94, 94, 94)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel7)
                        .addGap(54, 54, 54)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103)
                        .addComponent(jRadioButton13)
                        .addGap(50, 50, 50)
                        .addComponent(jRadioButton8)
                        .addGap(62, 62, 62)
                        .addComponent(jRadioButton9)
                        .addGap(94, 94, 94)
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel8)
                        .addGap(34, 34, 34)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103)
                        .addComponent(jRadioButton7)
                        .addGap(50, 50, 50)
                        .addComponent(jRadioButton11)
                        .addGap(55, 55, 55)
                        .addComponent(jRadioButton12)
                        .addGap(87, 87, 87)
                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel9)
                        .addGap(20, 20, 20)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103)
                        .addComponent(jRadioButton10)
                        .addGap(50, 50, 50)
                        .addComponent(jRadioButton14)
                        .addGap(62, 62, 62)
                        .addComponent(jRadioButton15)
                        .addGap(87, 87, 87)
                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel10)
                        .addGap(555, 555, 555)
                        .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jButton1)
                        .addGap(483, 483, 483)
                        .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jButton2)
                        .addGap(494, 494, 494)
                        .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jButton3)
                        .addGap(192, 192, 192)
                        .addComponent(jLabel11)
                        .addGap(17, 17, 17)
                        .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jButton4)))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel5))
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jRadioButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jRadioButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jRadioButton3))
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jRadioButton4)
                            .addComponent(jRadioButton5)
                            .addComponent(jRadioButton6))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton13)
                    .addComponent(jRadioButton8)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jRadioButton9))
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jRadioButton7)
                            .addComponent(jRadioButton11)
                            .addComponent(jRadioButton12))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jRadioButton10)
                            .addComponent(jRadioButton14)
                            .addComponent(jRadioButton15))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel10))
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel11))
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jButton4))
        );

        jTextField1.getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        LanguageDialog dlg = new LanguageDialog((java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this), true);
        dlg.setLocationRelativeTo(this);
        dlg.setVisible(true);

        String picked = dlg.getChosenLanguage();
        if (picked != null) {
            currentLanguage = picked;
            refreshCurrentLanguageUI();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            //  External Input (EI): jTextField1 * (jRadioButton1/2/3) -> jTextField6 
            int EI = 0;
            String s1 = jTextField1.getText().trim();
            if (!s1.isEmpty()) {
                EI = Integer.parseInt(s1);
            }
            if (EI < 0) {
                throw new NumberFormatException();
            }

            int w1;
            if (jRadioButton1.isSelected()) {
                w1 = 3;
            } else if (jRadioButton2.isSelected()) {
                w1 = 4;
            } else if (jRadioButton3.isSelected()) {
                w1 = 6;
            } else {
                w1 = 4;
            }

            int total1 = EI * w1;
            jTextField6.setText(String.valueOf(total1));

            //  External Output (EO): jTextField2 * (jRadioButton4/5/6) -> jTextField7 
            int EO = 0;
            String s2 = jTextField2.getText().trim();
            if (!s2.isEmpty()) {
                EO = Integer.parseInt(s2);
            }
            if (EO < 0) {
                throw new NumberFormatException();
            }

            int w2;
            if (jRadioButton4.isSelected()) {
                w2 = 4;
            } else if (jRadioButton5.isSelected()) {
                w2 = 5;
            } else if (jRadioButton6.isSelected()) {
                w2 = 7;
            } else {
                w2 = 5;
            }

            int total2 = EO * w2;
            jTextField7.setText(String.valueOf(total2));

            // External InQuries (EQ): jTextField3 * (jRadioButton7/8/9) -> jTextField8 
            int EQ = 0;
            String s3 = jTextField3.getText().trim();
            if (!s3.isEmpty()) {
                EQ = Integer.parseInt(s3);
            }
            if (EQ < 0) {
                throw new NumberFormatException();
            }

            int w3;
            if (jRadioButton7.isSelected()) {
                w3 = 3;
            } else if (jRadioButton8.isSelected()) {
                w3 = 4;
            } else if (jRadioButton9.isSelected()) {
                w3 = 6;
            } else {
                w3 = 4;
            }

            int total3 = EQ * w3;
            jTextField8.setText(String.valueOf(total3));

            //  Internal Logical Files (ILF): jTextField4 * (jRadioButton10/11/12) -> jTextField9 =====
            int ILF = 0;
            String s4 = jTextField4.getText().trim();
            if (!s4.isEmpty()) {
                ILF = Integer.parseInt(s4);
            }
            if (ILF < 0) {
                throw new NumberFormatException();
            }

            int w4;
            if (jRadioButton10.isSelected()) {
                w4 = 7;
            } else if (jRadioButton11.isSelected()) {
                w4 = 10;
            } else if (jRadioButton12.isSelected()) {
                w4 = 15;
            } else {
                w4 = 10;
            }

            int total4 = ILF * w4;
            jTextField9.setText(String.valueOf(total4));

            //  External Interface Files (EIF) : jTextField5 * (jRadioButton13/14/15) -> jTextField10 =====
            int EIF = 0;
            String s5 = jTextField5.getText().trim();
            if (!s5.isEmpty()) {
                EIF = Integer.parseInt(s5);
            }
            if (EIF < 0) {
                throw new NumberFormatException();
            }

            int w5;
            if (jRadioButton13.isSelected()) {
                w5 = 5;
            } else if (jRadioButton14.isSelected()) {
                w5 = 7;
            } else if (jRadioButton15.isSelected()) {
                w5 = 10;
            } else {
                w5 = 7;
            }

            int total5 = EIF * w5;
            jTextField10.setText(String.valueOf(total5));

            // Total Count (sum of row totals) -> jTextField11 
            int totalCount = total1 + total2 + total3 + total4 + total5;
            jTextField11.setText(String.valueOf(totalCount));
            
            double vaf = 0.65 + 0.01 * vafSum;
            double fp = totalCount * vaf;

            // Show FP in jTextField13 (use this as FP result)
            jTextField13.setText(String.format("%,.2f", fp));

        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Enter non-negative integers only in the Count fields (blank = 0).",
                    "Invalid input",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        java.awt.Frame frame = (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this);

        // Pass existing values so the dialog shows saved choices
        ValueAdjustmentDialog dlg = new ValueAdjustmentDialog(frame, true, vafValues);
        dlg.setLocationRelativeTo(this);
        dlg.setVisible(true);

        if (!dlg.isApproved()) return;

        // Save values back into this panel
        vafValues = dlg.getValues();
        vafSum = dlg.getSum();

        // Show VAF sum in the UI (pick the correct text field for your layout)
        jTextField14.setText(String.valueOf(vafSum));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String fpText = jTextField13.getText().trim();
        if (fpText.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Compute FP first.");
            return;
        }

        double fp;
        try {
            fp = Double.parseDouble(fpText.replace(",", ""));
        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "FP value is invalid.");
            return;
        }

        String lang = (currentLanguage == null || currentLanguage.isBlank()) ? "None" : currentLanguage;
        int loc = locPerFp(lang);
        if (loc < 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Select a valid language first.");
            return;
        }

        double size = fp * loc;

        // Show code size in jTextField15
        jTextField15.setText(String.format("%,.0f", size));
    }//GEN-LAST:event_jButton3ActionPerformed

    private static int parseNonNegInt(String s) {
       if (s == null) return 0;
       s = s.trim();
       if (s.isEmpty()) return 0;
       int v = Integer.parseInt(s);
       return Math.max(v, 0);
   }

   private static void selectRadio(javax.swing.JRadioButton... radios) {
       for (javax.swing.JRadioButton r : radios) {
           if (r != null) r.setSelected(false);
       }
   }

   private static int getSelectedWeight(javax.swing.JRadioButton r1, int v1,
                                        javax.swing.JRadioButton r2, int v2,
                                        javax.swing.JRadioButton r3, int v3,
                                        int defaultVal) {
       if (r1.isSelected()) return v1;
       if (r2.isSelected()) return v2;
       if (r3.isSelected()) return v3;
       return defaultVal;
   }

   private static void setSelectedWeight(int val,
                                         javax.swing.JRadioButton r1, int v1,
                                         javax.swing.JRadioButton r2, int v2,
                                         javax.swing.JRadioButton r3, int v3,
                                         int defaultVal) {
       // clear first
       r1.setSelected(false);
       r2.setSelected(false);
       r3.setSelected(false);

       if (val == v1) r1.setSelected(true);
       else if (val == v2) r2.setSelected(true);
       else if (val == v3) r3.setSelected(true);
       else {
           // fallback to default
           if (defaultVal == v1) r1.setSelected(true);
           else if (defaultVal == v2) r2.setSelected(true);
           else if (defaultVal == v3) r3.setSelected(true);
       }
   } 
   
   public java.util.Properties toProperties() {
        java.util.Properties p = new java.util.Properties();

        // language
        p.setProperty("language", (currentLanguage == null) ? "" : currentLanguage);

        // counts
        p.setProperty("count.ei", jTextField1.getText().trim());
        p.setProperty("count.eo", jTextField2.getText().trim());
        p.setProperty("count.eq", jTextField3.getText().trim());
        p.setProperty("count.ilf", jTextField4.getText().trim());
        p.setProperty("count.eif", jTextField5.getText().trim());

        // selected weights (store the numeric weight)
        int wEI  = getSelectedWeight(jRadioButton1,3, jRadioButton2,4, jRadioButton3,6, 4);
        int wEO  = getSelectedWeight(jRadioButton4,4, jRadioButton5,5, jRadioButton6,7, 5);
        int wEQ  = getSelectedWeight(jRadioButton13,3, jRadioButton8,4, jRadioButton9,6, 4);
        int wILF = getSelectedWeight(jRadioButton7,7, jRadioButton11,10, jRadioButton12,15, 10);
        int wEIF = getSelectedWeight(jRadioButton10,5, jRadioButton14,7, jRadioButton15,10, 7);

        p.setProperty("weight.ei",  String.valueOf(wEI));
        p.setProperty("weight.eo",  String.valueOf(wEO));
        p.setProperty("weight.eq",  String.valueOf(wEQ));
        p.setProperty("weight.ilf", String.valueOf(wILF));
        p.setProperty("weight.eif", String.valueOf(wEIF));

        // computed fields (optional)
        p.setProperty("total.ei",  jTextField6.getText().trim());
        p.setProperty("total.eo",  jTextField7.getText().trim());
        p.setProperty("total.eq",  jTextField8.getText().trim());
        p.setProperty("total.ilf", jTextField9.getText().trim());
        p.setProperty("total.eif", jTextField10.getText().trim());
        p.setProperty("total.count", jTextField11.getText().trim());

        p.setProperty("fp.value", jTextField13.getText().trim());
        p.setProperty("vaf.sum",  jTextField14.getText().trim());
        p.setProperty("code.size", jTextField15.getText().trim());

        // VAF values (for now store 14 ints if you already have them; otherwise keep zeros)
        // If you don’t have vafValues array yet, add: private int[] vafValues = new int[14];
        for (int i = 0; i < 14; i++) {
            int v = 0;
            if (this.vafValues != null && this.vafValues.length == 14) v = this.vafValues[i];
            p.setProperty("vaf." + (i + 1), String.valueOf(v));
        }

        return p;
    }

    public void loadFromProperties(java.util.Properties p) {
        // language
        String lang = p.getProperty("language", "").trim();
        if (!lang.isEmpty()) {
            currentLanguage = lang;
            refreshCurrentLanguageUI(); // updates jTextField12
        }

        // counts
        jTextField1.setText(p.getProperty("count.ei", ""));
        jTextField2.setText(p.getProperty("count.eo", ""));
        jTextField3.setText(p.getProperty("count.eq", ""));
        jTextField4.setText(p.getProperty("count.ilf", ""));
        jTextField5.setText(p.getProperty("count.eif", ""));

        // weights
        int wEI  = Integer.parseInt(p.getProperty("weight.ei",  "4"));
        int wEO  = Integer.parseInt(p.getProperty("weight.eo",  "5"));
        int wEQ  = Integer.parseInt(p.getProperty("weight.eq",  "4"));
        int wILF = Integer.parseInt(p.getProperty("weight.ilf", "10"));
        int wEIF = Integer.parseInt(p.getProperty("weight.eif", "7"));

        setSelectedWeight(wEI,  jRadioButton1,3, jRadioButton2,4, jRadioButton3,6, 4);
        setSelectedWeight(wEO,  jRadioButton4,4, jRadioButton5,5, jRadioButton6,7, 5);
        setSelectedWeight(wEQ,  jRadioButton13,3, jRadioButton8,4, jRadioButton9,6, 4);
        setSelectedWeight(wILF, jRadioButton7,7, jRadioButton11,10, jRadioButton12,15, 10);
        setSelectedWeight(wEIF, jRadioButton10,5, jRadioButton14,7, jRadioButton15,10, 7);

        // computed fields (optional)
        jTextField6.setText(p.getProperty("total.ei", ""));
        jTextField7.setText(p.getProperty("total.eo", ""));
        jTextField8.setText(p.getProperty("total.eq", ""));
        jTextField9.setText(p.getProperty("total.ilf", ""));
        jTextField10.setText(p.getProperty("total.eif", ""));
        jTextField11.setText(p.getProperty("total.count", ""));

        jTextField13.setText(p.getProperty("fp.value", ""));
        jTextField14.setText(p.getProperty("vaf.sum", ""));
        jTextField15.setText(p.getProperty("code.size", ""));

        // VAF values
        if (this.vafValues == null || this.vafValues.length != 14) this.vafValues = new int[14];
        
        for (int i = 0; i < 14; i++) {
            String key = "vaf." + (i + 1);
            String val = p.getProperty(key, "0");
            try {
                this.vafValues[i] = parseNonNegInt(val);
            } catch (Exception ex) {
                this.vafValues[i] = 0;
            }
        }
        vafSum = 0;
        for (int i = 0; i < 14; i++) {
            vafSum += vafValues[i];
        }
        jTextField14.setText(String.valueOf(vafSum));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
