/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;
import java.io.File;

/**
 *
 * @author shree
 */
public class MainFrame extends javax.swing.JFrame {

    //ProjectDialogComponents
    private String projectName = null;
    private String productName = null;
    private String creatorName = null;
    private String projectComments = null;
    private String selectedLanguage = "None";

    //Project Title Name 
    private void updateTitleBar() {
        if (projectName == null || projectName.isBlank()) {
            setTitle("CECS 544 Metrics Suite");
        } else {
            setTitle("CECS 544 Metrics Suite - " + projectName);
        }
    }

    //Function Points TAbbed Pane Name
    private boolean tabTitleExists(String candidate) {
        for (int i = 0; i < jTabbedPane1.getTabCount(); i++) {
            if (candidate.equals(jTabbedPane1.getTitleAt(i))) {
                return true;
            }
        }
        return false;
    }

    //Current Language in FP pane
    public void setSelectedLanguage(String lang) {
        selectedLanguage = (lang == null || lang.isBlank()) ? "None" : lang;

    }

    public String getSelectedLanguage() {
        return selectedLanguage;
    }

    //To Save the whole project along with FP metric files- 2 helper methods
    private static void putAllWithPrefix(java.util.Properties dest,
            String prefix,
            java.util.Properties src) {
        for (String k : src.stringPropertyNames()) {
            dest.setProperty(prefix + k, src.getProperty(k));
        }
    }

    private static java.util.Properties subProperties(java.util.Properties src,
            String prefix) {
        java.util.Properties out = new java.util.Properties();
        for (String k : src.stringPropertyNames()) {
            if (k.startsWith(prefix)) {
                out.setProperty(k.substring(prefix.length()), src.getProperty(k));
            }
        }
        return out;
    }

    public MainFrame() {
        initComponents();
        jMenu5.setVisible(false);
        updateTitleBar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CECS 544 Metrics Suite");

        jTabbedPane1.setName("mainTabbedPane"); // NOI18N

        jMenu1.setText("File");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("New");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Open");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Save");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);
        jMenu1.add(jSeparator1);

        jMenuItem4.setText("Exit");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Preferences");

        jMenuItem5.setText("Language");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Metrics");

        jMenu7.setText("Function Points");

        jMenuItem6.setText("Enter FP Data");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem6);

        jMenu4.add(jMenu7);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Project Code");
        jMenu5.setEnabled(false);
        jMenuBar1.add(jMenu5);

        jMenu6.setText("Help");
        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 100, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        NewProjectJDialog dlg = new NewProjectJDialog(this, true);
        dlg.setLocationRelativeTo(this);
        dlg.setVisible(true);

        if (!dlg.isApproved()) {
            return; // user cancelled
        }

// Save project metadata
        projectName = dlg.getProjectName();
        productName = dlg.getProductName();
        creatorName = dlg.getCreator();
        projectComments = dlg.getComments();

// Clear ALL panes/tabs for a truly new project
        jTabbedPane1.removeAll();

// Update window title
        updateTitleBar();

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        LanguageDialog dlg = new LanguageDialog(this, true, selectedLanguage);
        dlg.setLocationRelativeTo(this);
        dlg.setVisible(true);

        String chose = dlg.getChosenLanguage();
        if (chose != null) {
            setSelectedLanguage(chose);
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        String name = javax.swing.JOptionPane.showInputDialog(
                this,
                "Enter name for the Function Points pane:",
                "New Function Points Pane",
                javax.swing.JOptionPane.QUESTION_MESSAGE
        );

        // Cancel pressed
        if (name == null) {
            return;
        }

        name = name.trim();

        // Empty name -> default
        if (name.isEmpty()) {
            name = "Function Points";
        }

        // Avoid duplicate tab titles by appending (2), (3), ...
        String base = name;
        int suffix = 2;
        while (tabTitleExists(name)) {
            name = base + " (" + suffix + ")";
            suffix++;
        }

        // Create pane + set current language + add tab
        FunctionPointsPanel fp = new FunctionPointsPanel();
        fp.setCurrentLanguage(selectedLanguage);
        jTabbedPane1.addTab(name, fp);
        jTabbedPane1.setSelectedComponent(fp);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed

        // Must have a project name (optional, but typical)
        if (projectName == null || projectName.isBlank()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Create a project first (File → New).");
            return;
        }

        javax.swing.JFileChooser chooser = new javax.swing.JFileChooser();
        chooser.setDialogTitle("Save Project");
        chooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Metrics Suite (*.ms)", "ms"));

        String safeProject = projectName.trim().replaceAll("[\\\\/:*?\"<>|]", "_");
        chooser.setSelectedFile(new java.io.File(safeProject + ".ms"));

        int result = chooser.showSaveDialog(this);
        if (result != javax.swing.JFileChooser.APPROVE_OPTION) {
            return;
        }

        File file = chooser.getSelectedFile();

        File dir = file.getParentFile();
        File target = new File(dir, safeProject + ".ms");

// If user chose a different name, inform them (optional)
        if (!target.getName().equalsIgnoreCase(file.getName())) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Saving project using the project name:\n" + target.getName(),
                    "Filename adjusted",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE
            );
        }

        file = target;

        if (file.exists()) {
            int choice = javax.swing.JOptionPane.showConfirmDialog(
                    this,
                    "File already exists:\n" + file.getName() + "\n\nReplace it?",
                    "Confirm overwrite",
                    javax.swing.JOptionPane.YES_NO_OPTION,
                    javax.swing.JOptionPane.WARNING_MESSAGE
            );
            if (choice != javax.swing.JOptionPane.YES_OPTION) {
                return; // user cancelled overwrite
            }
        }

        java.util.Properties props = new java.util.Properties();

        // ---- project metadata (4.35 / 4.37) ----
        if (projectName != null) {
            props.setProperty("project.name", projectName);
        }
        if (productName != null) {
            props.setProperty("product.name", productName);
        }
        if (creatorName != null) {
            props.setProperty("creator.name", creatorName);
        }
        if (projectComments != null) {
            props.setProperty("project.comments", projectComments);
        }

        // ---- panes (4.35) ----
        int paneCount = jTabbedPane1.getTabCount();
        props.setProperty("panes.count", String.valueOf(paneCount));

        for (int i = 0; i < paneCount; i++) {
            java.awt.Component c = jTabbedPane1.getComponentAt(i);
            String title = jTabbedPane1.getTitleAt(i);

            props.setProperty("pane." + i + ".title", title);

            if (c instanceof FunctionPointsPanel fp) {
                props.setProperty("pane." + i + ".type", "fp");

                java.util.Properties paneProps = fp.toProperties();
                putAllWithPrefix(props, "pane." + i + ".", paneProps);

            } else {
                // unknown pane type (future metrics)
                props.setProperty("pane." + i + ".type", "unknown");
            }
        }

        try (java.io.FileOutputStream out = new java.io.FileOutputStream(file)) {
            props.store(out, "CECS 544 Metrics Suite Project");
            javax.swing.JOptionPane.showMessageDialog(this, "Saved: " + file.getName());
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Save failed: " + ex.getMessage());
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        javax.swing.JFileChooser chooser = new javax.swing.JFileChooser();
        chooser.setDialogTitle("Open Project");
        chooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Metrics Suite (*.ms)", "ms"));

        int result = chooser.showOpenDialog(this);
        if (result != javax.swing.JFileChooser.APPROVE_OPTION) {
            return;
        }

        java.io.File file = chooser.getSelectedFile();

        java.util.Properties props = new java.util.Properties();
        try (java.io.FileInputStream in = new java.io.FileInputStream(file)) {
            props.load(in);
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Open failed: " + ex.getMessage());
            return;
        }

        // ---- project metadata ----
        projectName = props.getProperty("project.name", "");
        productName = props.getProperty("product.name", "");
        creatorName = props.getProperty("creator.name", "");
        projectComments = props.getProperty("project.comments", "");
        updateTitleBar();

        // ---- clear current tabs ----
        jTabbedPane1.removeAll();

        // ---- load panes ----
        int paneCount = 0;
        try {
            paneCount = Integer.parseInt(props.getProperty("panes.count", "0"));
        } catch (NumberFormatException ignored) {
        }

        for (int i = 0; i < paneCount; i++) {
            String type = props.getProperty("pane." + i + ".type", "unknown");
            String title = props.getProperty("pane." + i + ".title", "Pane " + (i + 1));

            if ("fp".equals(type)) {
                FunctionPointsPanel fp = new FunctionPointsPanel();

                java.util.Properties paneProps = subProperties(props, "pane." + i + ".");
                fp.loadFromProperties(paneProps);

                jTabbedPane1.addTab(title, fp);
            } else {
                // future: other metric pane types
            }
        }

        if (jTabbedPane1.getTabCount() > 0) {
            jTabbedPane1.setSelectedIndex(0);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        
        System.exit(0);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
