/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

/**
 *
 * @author bharg
 */
public class UseCasePointsPanel extends javax.swing.JPanel {

    /**
     * Creates new form UseCasePointsPanel
     */
    public UseCasePointsPanel() {
        initComponents();
        setDefaults();
    }

    private int[] tcfValues = new int[13];
    private double currentTCF = 0.60;
    private int[] ecfValues = new int[8];
    private double currentECF = 1.40;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // </editor-fold>
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextFieldUUCP = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldProductivityFactor = new javax.swing.JTextField();
        jTextFieldECF = new javax.swing.JTextField();
        jTextFieldTCF = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldTotalUCP = new javax.swing.JTextField();
        jButtonComputeUCP = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTextActorSimpleTotal = new javax.swing.JTextField();
        jTextActorAverageTotal = new javax.swing.JTextField();
        jTextActorComplexTotal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextActorSimpleCount = new javax.swing.JTextField();
        jTextActorAverageCount = new javax.swing.JTextField();
        jTextActorComplexCount = new javax.swing.JTextField();
        jTextFieldUAWTotal = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextUseCaseAverageTotal = new javax.swing.JTextField();
        jTextUseCaseComplexTotal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextUseCaseSimpleCount = new javax.swing.JTextField();
        jTextUseCaseAverageCount = new javax.swing.JTextField();
        jTextUseCaseComplexCount = new javax.swing.JTextField();
        jTextFieldUUCWTotal = new javax.swing.JTextField();
        jTextUseCaseSimpleTotal = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldLOCPerUCP = new javax.swing.JTextField();
        jTextFieldLOCPerPM = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldEstimatedLOC = new javax.swing.JTextField();
        jTextFieldEstimatedHours = new javax.swing.JTextField();
        jTextFieldEstimatedPM = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(900, 600));

        jButton1.setText("Calculate Technical Complexity Factor");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Calculate Environmental Complexity Factor");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jTextFieldUUCP.setEditable(false);
        jTextFieldUUCP.addActionListener(this::jTextFieldUUCPActionPerformed);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Enter Productivity Factor");
        jLabel11.setToolTipText("PF is the ratio of person-hours per use case as determined from past projects");

        jTextFieldProductivityFactor.addActionListener(this::jTextFieldProductivityFactorActionPerformed);

        jTextFieldECF.setEditable(false);

        jTextFieldTCF.setEditable(false);
        jTextFieldTCF.addActionListener(this::jTextFieldTCFActionPerformed);

        jLabel14.setText("Total Use Case Points");

        jTextFieldTotalUCP.setEditable(false);

        jButtonComputeUCP.setText("Compute UCP");
        jButtonComputeUCP.addActionListener(this::jButtonComputeUCPActionPerformed);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Unadjusted Actor Weight (UAW)"));

        jTextActorSimpleTotal.setEditable(false);
        jTextActorSimpleTotal.addActionListener(this::jTextActorSimpleTotalActionPerformed);

        jTextActorAverageTotal.setEditable(false);
        jTextActorAverageTotal.addActionListener(this::jTextActorAverageTotalActionPerformed);

        jTextActorComplexTotal.setEditable(false);

        jLabel2.setText("Simple Actors (x1)");
        jLabel2.setToolTipText("Another system with a defined API (weight = 1)");

        jLabel3.setText("Average Actors (x2)");
        jLabel3.setToolTipText("Another system acting via a protocol like TCP/IP or ASP (weight = 2)");

        jLabel4.setText("Complex Actors (x3)");
        jLabel4.setToolTipText("A human (weight = 3)");

        jLabel5.setText("Total UAW");

        jTextFieldUAWTotal.setEditable(false);

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Count");

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Result");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel5)))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jTextFieldUAWTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextActorComplexCount, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextActorAverageCount, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextActorSimpleCount, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextActorSimpleTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextActorAverageTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextActorComplexTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextActorSimpleCount, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextActorSimpleTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextActorAverageCount, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextActorAverageTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextActorComplexTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextActorComplexCount, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldUAWTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(14, 14, 14))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Unadjusted Use Case Weight (UUCW)"));

        jTextUseCaseAverageTotal.setEditable(false);
        jTextUseCaseAverageTotal.addActionListener(this::jTextUseCaseAverageTotalActionPerformed);

        jTextUseCaseComplexTotal.setEditable(false);

        jLabel6.setText("Simple Use Cases (x5)");
        jLabel6.setToolTipText("A simple user interface, one db entity, 3 or less steps in success scenario, less than 5 classes (weight = 5)");

        jLabel7.setText("Average Use Cases (x10)");
        jLabel7.setToolTipText("Multiple UI components, 2 or more DB entities, 4 to 7 steps, and 5 to 10 classes (weight = 10)");

        jLabel8.setText("Complex Use Cases (x15)");
        jLabel8.setToolTipText("Complex UI, 3 or more DB entities, over 7 steps, more than 10 classes (weight = 15)");

        jLabel9.setText("Total UUCW");

        jTextUseCaseAverageCount.addActionListener(this::jTextUseCaseAverageCountActionPerformed);

        jTextUseCaseComplexCount.addActionListener(this::jTextUseCaseComplexCountActionPerformed);

        jTextFieldUUCWTotal.setEditable(false);

        jTextUseCaseSimpleTotal.setEditable(false);

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Count");

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Result");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel9)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextUseCaseComplexCount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextUseCaseAverageCount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextUseCaseSimpleCount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextUseCaseSimpleTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextUseCaseAverageTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextUseCaseComplexTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldUUCWTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextUseCaseSimpleCount, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextUseCaseSimpleTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextUseCaseAverageCount, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextUseCaseAverageTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextUseCaseComplexCount, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextUseCaseComplexTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldUUCWTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Use Case Points Estimation");

        jButton3.setText("Calculate Unadjusted Use Case Points");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Lines of Code"));

        jLabel13.setText("LOC per UCP");

        jLabel12.setText("LOC per PM");

        jTextFieldLOCPerUCP.addActionListener(this::jTextFieldLOCPerUCPActionPerformed);

        jTextFieldLOCPerPM.addActionListener(this::jTextFieldLOCPerPMActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldLOCPerUCP, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldLOCPerPM, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldLOCPerUCP, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldLOCPerPM, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Estimates"));

        jLabel16.setText("Estimated LOC");

        jLabel15.setText("Estimated Hours");

        jLabel17.setText("Estimated PM");

        jTextFieldEstimatedLOC.setEditable(false);

        jTextFieldEstimatedHours.setEditable(false);
        jTextFieldEstimatedHours.addActionListener(this::jTextFieldEstimatedHoursActionPerformed);

        jTextFieldEstimatedPM.setEditable(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldEstimatedHours, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldEstimatedLOC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldEstimatedPM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jTextFieldEstimatedPM, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextFieldEstimatedHours, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTextFieldEstimatedLOC, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButtonComputeUCP, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldUUCP, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldTCF, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldECF, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldProductivityFactor, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jTextFieldTotalUCP, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(jLabel1)))
                .addContainerGap(247, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addGap(12, 12, 12)
                                .addComponent(jButton1)
                                .addGap(12, 12, 12)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldUUCP, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jTextFieldTCF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jTextFieldECF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldProductivityFactor, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(7, 7, 7))
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonComputeUCP, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldTotalUCP, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void setDefaults() {
        jTextFieldProductivityFactor.setText("20");
        jTextFieldLOCPerPM.setText("700");
        jTextFieldLOCPerUCP.setText("100");

        jTextFieldTCF.setText("0.60");
        jTextFieldECF.setText("1.40");

        jTextFieldTCF.setEditable(false);
        jTextFieldECF.setEditable(false);

        jTextActorSimpleTotal.setEditable(false);
        jTextActorAverageTotal.setEditable(false);
        jTextActorComplexTotal.setEditable(false);
        jTextFieldUAWTotal.setEditable(false);

        jTextUseCaseSimpleTotal.setEditable(false);
        jTextUseCaseAverageTotal.setEditable(false);
        jTextUseCaseComplexTotal.setEditable(false);
        jTextFieldUUCWTotal.setEditable(false);

        jTextFieldUUCP.setEditable(false);
        jTextFieldTotalUCP.setEditable(false);
        jTextFieldEstimatedHours.setEditable(false);
        jTextFieldEstimatedLOC.setEditable(false);
        jTextFieldEstimatedPM.setEditable(false);
    }

    private int parseIntField(javax.swing.JTextField tf) {
        String s = tf.getText().trim();
        if (s.isEmpty()) {
            return 0;
        }
        int v = Integer.parseInt(s);
        if (v < 0) {
            throw new NumberFormatException();
        }
        return v;
    }

    private double parseDoubleField(javax.swing.JTextField tf) {
        String s = tf.getText().trim();
        if (s.isEmpty()) {
            return 0.0;
        }
        double v = Double.parseDouble(s);
        if (v < 0) {
            throw new NumberFormatException();
        }
        return v;
    }

    private void recomputeUCPBaseValues() {

        // Actor counts
        int simpleActors = parseIntField(jTextActorSimpleCount);
        int averageActors = parseIntField(jTextActorAverageCount);
        int complexActors = parseIntField(jTextActorComplexCount);

        // Use case counts
        int simpleUC = parseIntField(jTextUseCaseSimpleCount);
        int averageUC = parseIntField(jTextUseCaseAverageCount);
        int complexUC = parseIntField(jTextUseCaseComplexCount);

        // Actor totals
        int actorSimpleTotal = simpleActors * 1;
        int actorAverageTotal = averageActors * 2;
        int actorComplexTotal = complexActors * 3;

        int uaw = actorSimpleTotal + actorAverageTotal + actorComplexTotal;

        // Use case totals
        int ucSimpleTotal = simpleUC * 5;
        int ucAverageTotal = averageUC * 10;
        int ucComplexTotal = complexUC * 15;

        int uucw = ucSimpleTotal + ucAverageTotal + ucComplexTotal;

        int uucp = uaw + uucw;

        // Update UI
        jTextActorSimpleTotal.setText(String.valueOf(actorSimpleTotal));
        jTextActorAverageTotal.setText(String.valueOf(actorAverageTotal));
        jTextActorComplexTotal.setText(String.valueOf(actorComplexTotal));

        jTextUseCaseSimpleTotal.setText(String.valueOf(ucSimpleTotal));
        jTextUseCaseAverageTotal.setText(String.valueOf(ucAverageTotal));
        jTextUseCaseComplexTotal.setText(String.valueOf(ucComplexTotal));

        jTextFieldUAWTotal.setText(String.valueOf(uaw));
        jTextFieldUUCWTotal.setText(String.valueOf(uucw));
        jTextFieldUUCP.setText(String.valueOf(uucp));
    }

    private void jTextActorSimpleTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextActorSimpleTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextActorSimpleTotalActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        java.awt.Frame frame = (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this);

        TechnicalComplexityDialog dlg = new TechnicalComplexityDialog(frame, true, tcfValues);
        dlg.setLocationRelativeTo(this);
        dlg.setVisible(true);

        if (!dlg.isApproved()) {
            return;
        }

        tcfValues = dlg.getValues();
        currentTCF = dlg.getTCF();

        jTextFieldTCF.setText(String.format("%.2f", currentTCF));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextUseCaseAverageCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextUseCaseAverageCountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextUseCaseAverageCountActionPerformed

    private void jTextActorAverageTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextActorAverageTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextActorAverageTotalActionPerformed

    private void jTextUseCaseAverageTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextUseCaseAverageTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextUseCaseAverageTotalActionPerformed

    private void jTextUseCaseComplexCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextUseCaseComplexCountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextUseCaseComplexCountActionPerformed

    private void jTextFieldTCFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTCFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTCFActionPerformed

    private void jTextFieldUUCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUUCPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUUCPActionPerformed

    private void jTextFieldEstimatedHoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEstimatedHoursActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEstimatedHoursActionPerformed

    private void jTextFieldProductivityFactorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldProductivityFactorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldProductivityFactorActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        java.awt.Frame frame = (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this);

        EnvironmentalComplexityDialog dlg = new EnvironmentalComplexityDialog(frame, true, ecfValues);
        dlg.setLocationRelativeTo(this);
        dlg.setVisible(true);

        if (!dlg.isApproved()) {
            return;
        }

        ecfValues = dlg.getValues();
        currentECF = dlg.getECF();

        jTextFieldECF.setText(String.format("%.2f", currentECF));

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonComputeUCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComputeUCPActionPerformed
        try {
            recomputeUCPBaseValues();

            double tcf = parseDoubleField(jTextFieldTCF);
            double ecf = parseDoubleField(jTextFieldECF);
            double productivity = parseDoubleField(jTextFieldProductivityFactor);
            double locPerPM = parseDoubleField(jTextFieldLOCPerPM);
            double locPerUCP = parseDoubleField(jTextFieldLOCPerUCP);

            double uucp = Double.parseDouble(jTextFieldUUCP.getText().trim());

            double totalUCP = uucp * tcf * ecf;
            double estimatedHours = totalUCP * productivity;
            double estimatedLOC = totalUCP * locPerUCP;
            double estimatedPM = (locPerPM == 0) ? 0 : estimatedLOC / locPerPM;

            jTextFieldTotalUCP.setText(String.format("%,.2f", totalUCP));
            jTextFieldEstimatedHours.setText(String.format("%,.2f", estimatedHours));
            jTextFieldEstimatedLOC.setText(String.format("%,.2f", estimatedLOC));
            jTextFieldEstimatedPM.setText(String.format("%,.2f", estimatedPM));

        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Enter valid non-negative numbers.",
                    "Invalid input",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_jButtonComputeUCPActionPerformed

    private void jTextFieldLOCPerUCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLOCPerUCPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLOCPerUCPActionPerformed

    private void jTextFieldLOCPerPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLOCPerPMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLOCPerPMActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            recomputeUCPBaseValues();
        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Enter valid non-negative numbers.",
                    "Invalid input",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    public java.util.Properties toProperties() {
        java.util.Properties p = new java.util.Properties();

        p.setProperty("type", "ucp");

        p.setProperty("actor.simple.count", jTextActorSimpleCount.getText());
        p.setProperty("actor.average.count", jTextActorAverageCount.getText());
        p.setProperty("actor.complex.count", jTextActorComplexCount.getText());

        p.setProperty("actor.simple.total", jTextActorSimpleTotal.getText());
        p.setProperty("actor.average.total", jTextActorAverageTotal.getText());
        p.setProperty("actor.complex.total", jTextActorComplexTotal.getText());
        p.setProperty("uaw.total", jTextFieldUAWTotal.getText());

        p.setProperty("uc.simple.count", jTextUseCaseSimpleCount.getText());
        p.setProperty("uc.average.count", jTextUseCaseAverageCount.getText());
        p.setProperty("uc.complex.count", jTextUseCaseComplexCount.getText());

        p.setProperty("uc.simple.total", jTextUseCaseSimpleTotal.getText());
        p.setProperty("uc.average.total", jTextUseCaseAverageTotal.getText());
        p.setProperty("uc.complex.total", jTextUseCaseComplexTotal.getText());
        p.setProperty("uucw.total", jTextFieldUUCWTotal.getText());

        p.setProperty("uucp", jTextFieldUUCP.getText());
        p.setProperty("tcf", jTextFieldTCF.getText());
        p.setProperty("ecf", jTextFieldECF.getText());
        p.setProperty("pf", jTextFieldProductivityFactor.getText());

        p.setProperty("loc.per.ucp", jTextFieldLOCPerUCP.getText());
        p.setProperty("loc.per.pm", jTextFieldLOCPerPM.getText());

        p.setProperty("total.ucp", jTextFieldTotalUCP.getText());
        p.setProperty("estimated.hours", jTextFieldEstimatedHours.getText());
        p.setProperty("estimated.loc", jTextFieldEstimatedLOC.getText());
        p.setProperty("estimated.pm", jTextFieldEstimatedPM.getText());

        for (int i = 0; i < tcfValues.length; i++) {
            p.setProperty("tcf.value." + i, String.valueOf(tcfValues[i]));
        }
        for (int i = 0; i < ecfValues.length; i++) {
            p.setProperty("ecf.value." + i, String.valueOf(ecfValues[i]));
        }

        return p;
    }

    private double parseStoredDouble(String s, double defaultValue) {
        try {
            return Double.parseDouble(s.trim().replace(",", ""));
        } catch (Exception e) {
            return defaultValue;
        }
    }

    public void loadFromProperties(java.util.Properties p) {
        jTextActorSimpleCount.setText(p.getProperty("actor.simple.count", "0"));
        jTextActorAverageCount.setText(p.getProperty("actor.average.count", "0"));
        jTextActorComplexCount.setText(p.getProperty("actor.complex.count", "0"));

        jTextActorSimpleTotal.setText(p.getProperty("actor.simple.total", ""));
        jTextActorAverageTotal.setText(p.getProperty("actor.average.total", ""));
        jTextActorComplexTotal.setText(p.getProperty("actor.complex.total", ""));
        jTextFieldUAWTotal.setText(p.getProperty("uaw.total", ""));

        jTextUseCaseSimpleCount.setText(p.getProperty("uc.simple.count", "0"));
        jTextUseCaseAverageCount.setText(p.getProperty("uc.average.count", "0"));
        jTextUseCaseComplexCount.setText(p.getProperty("uc.complex.count", "0"));

        jTextUseCaseSimpleTotal.setText(p.getProperty("uc.simple.total", ""));
        jTextUseCaseAverageTotal.setText(p.getProperty("uc.average.total", ""));
        jTextUseCaseComplexTotal.setText(p.getProperty("uc.complex.total", ""));
        jTextFieldUUCWTotal.setText(p.getProperty("uucw.total", ""));

        jTextFieldUUCP.setText(p.getProperty("uucp", ""));
        jTextFieldTCF.setText(p.getProperty("tcf", "0.60"));
        jTextFieldECF.setText(p.getProperty("ecf", "1.40"));
        jTextFieldProductivityFactor.setText(p.getProperty("pf", "20"));

        jTextFieldLOCPerUCP.setText(p.getProperty("loc.per.ucp", "100"));
        jTextFieldLOCPerPM.setText(p.getProperty("loc.per.pm", "700"));

        jTextFieldTotalUCP.setText(p.getProperty("total.ucp", ""));
        jTextFieldEstimatedHours.setText(p.getProperty("estimated.hours", ""));
        jTextFieldEstimatedLOC.setText(p.getProperty("estimated.loc", ""));
        jTextFieldEstimatedPM.setText(p.getProperty("estimated.pm", ""));

        for (int i = 0; i < tcfValues.length; i++) {
            tcfValues[i] = Integer.parseInt(p.getProperty("tcf.value." + i, "0"));
        }
        for (int i = 0; i < ecfValues.length; i++) {
            ecfValues[i] = Integer.parseInt(p.getProperty("ecf.value." + i, "0"));
        }

        currentTCF = parseStoredDouble(jTextFieldTCF.getText(), 0.60);
        currentECF = parseStoredDouble(jTextFieldECF.getText(), 1.40);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonComputeUCP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextActorAverageCount;
    private javax.swing.JTextField jTextActorAverageTotal;
    private javax.swing.JTextField jTextActorComplexCount;
    private javax.swing.JTextField jTextActorComplexTotal;
    private javax.swing.JTextField jTextActorSimpleCount;
    private javax.swing.JTextField jTextActorSimpleTotal;
    private javax.swing.JTextField jTextFieldECF;
    private javax.swing.JTextField jTextFieldEstimatedHours;
    private javax.swing.JTextField jTextFieldEstimatedLOC;
    private javax.swing.JTextField jTextFieldEstimatedPM;
    private javax.swing.JTextField jTextFieldLOCPerPM;
    private javax.swing.JTextField jTextFieldLOCPerUCP;
    private javax.swing.JTextField jTextFieldProductivityFactor;
    private javax.swing.JTextField jTextFieldTCF;
    private javax.swing.JTextField jTextFieldTotalUCP;
    private javax.swing.JTextField jTextFieldUAWTotal;
    private javax.swing.JTextField jTextFieldUUCP;
    private javax.swing.JTextField jTextFieldUUCWTotal;
    private javax.swing.JTextField jTextUseCaseAverageCount;
    private javax.swing.JTextField jTextUseCaseAverageTotal;
    private javax.swing.JTextField jTextUseCaseComplexCount;
    private javax.swing.JTextField jTextUseCaseComplexTotal;
    private javax.swing.JTextField jTextUseCaseSimpleCount;
    private javax.swing.JTextField jTextUseCaseSimpleTotal;
    // End of variables declaration//GEN-END:variables
}
